dev updates Sat 18 Jul 2015 07:50:43 BST

diff --git a/bin/ngseasy_sv_calling b/bin/ngseasy_sv_calling
--- a/bin/ngseasy_sv_calling
+++ b/bin/ngseasy_sv_calling
@@ -58,6 +58,7 @@ KNOWN_INDELS=""
 KNOWN_SNPS_1000G=""
 KNOWN_SNPS_OMNI=""
 KNOWN_SNPS_b138=""
+SPEEDSEQ_CONFIG=""
 
 base_qual="20"
 map_qual="20"
@@ -572,6 +573,19 @@ if [ "${CNV}" == "sv_lumpy" ]
   then
   docker images | grep ngseasy-speedseq 2>&1 || { echo "compbio/ngseasy-speedseq:${NGSEASYVERSION} not installed.  Aborting." >&2; exit 1; }
   logger_ngseasy "[${NGSEASY_STEP}]:START Variant Calling using speedseq:lumpy and svtyper " ${LOGFILE}
+
+## select config file based on genome build
+  if [[ "${GENOMEBUILD}" == "b37" ]]
+      then
+      SPEEDSEQ_CONFIG="/usr/local/pipeline/speedseq/bin/speedseq_b37.config"
+  elif [[ "${GENOMEBUILD}" == "hg19" ]]
+      SPEEDSEQ_CONFIG="/usr/local/pipeline/speedseq/bin/speedseq_hg19.config"
+  else
+    logger_ngseasy "[${NGSEASY_STEP}]:ERROR speedseq.config not set. Exiting" ${LOGFILE}
+    sleep 1s
+    exit 1
+  fi
+
   ${DOCKER_RUN} \
   -v ${PROJECT_DIR}:/home/pipeman/ngs_projects \
   --name sv_lumpy_${BAM_PREFIX} \
@@ -584,7 +598,8 @@ if [ "${CNV}" == "sv_lumpy" ]
   -t ${NCPU} \
   ${sv_options} \
   -T ${SOUTDocker}/tmp/${BAM_PREFIX}.raw.indels.${CNV}.XXXXXXXXXXXX \
-  -o ${SOUTDocker}/vcf/${BAM_PREFIX}.raw.indels.${CNV} && \
+  -o ${SOUTDocker}/vcf/${BAM_PREFIX}.raw.indels.${CNV} \
+  -X ${SPEEDSEQ_CONFIG} && \
   time zcat ${SOUTDocker}/vcf/${BAM_PREFIX}.raw.indels.${CNV}.vcf.gz | \
   vcffilter -f 'QUAL > 5' -s | \
   fix_ambiguous | \
