Minor

diff --git a/bin/ngseasy_fastqc b/bin/ngseasy_fastqc
--- a/bin/ngseasy_fastqc
+++ b/bin/ngseasy_fastqc
@@ -154,180 +154,178 @@ fi
 ########################################################################################################
 ## Read config and loop through all lines calling fastqc docker
 ##
-	
 while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18 f19 f20 f21 f22
 do
 
-	## set varibales  
-	#
-	PROJECT_ID=$f1
-	SAMPLE_ID=$f2
-	FASTQ1=$f3
-	FASTQ2=$f4
-	PROJECT_DIR=$f5
-	DNA_PREP_LIBRARY_ID=$f6
-	NGS_PLATFORM=$f7
-	NGS_TYPE=$f8
-	BAIT=$f9
-	CAPTURE=$f10
-	FASTQC=$f11
-	TRIM=$f12
-	BSQR=$f13
-	REALN=$f14
-	ALIGNER=$f15
-	VARCALLER=$f16
-	CNV=$f17
-	ANNOTATOR=$f18
-	CLEANUP=$f19
-	NCPU=$f20
-	VERSION=$f21
-	NGSUSER=$f22
-	DATE=`date +"%d%m%y"`
+## set varibales  
+#
+PROJECT_ID=$f1
+SAMPLE_ID=$f2
+FASTQ1=$f3
+FASTQ2=$f4
+PROJECT_DIR=$f5
+DNA_PREP_LIBRARY_ID=$f6
+NGS_PLATFORM=$f7
+NGS_TYPE=$f8
+BAIT=$f9
+CAPTURE=$f10
+FASTQC=$f11
+TRIM=$f12
+BSQR=$f13
+REALN=$f14
+ALIGNER=$f15
+VARCALLER=$f16
+CNV=$f17
+ANNOTATOR=$f18
+CLEANUP=$f19
+NCPU=$f20
+VERSION=$f21
+NGSUSER=$f22
+DATE=`date +"%d%m%y"`
 
-	## read config_file
-	logger_ngseasy "[ngseasy_fastqc]:
-	[$PROJECT_ID\t
-	$SAMPLE_ID\t
-	$FASTQ1\t
-	$FASTQ2\t
-	$PROJECT_DIR\t 
-	$DNA_PREP_LIBRARY_ID\t
-	$NGS_PLATFORM\t
-	$NGS_TYPE\t
-	$BAIT\t
-	$CAPTURE\t
-	$FASTQC\t
-	$TRIM\t
-	$BSQR\t
-	$REALN\t
-	$ALIGNER\t
-	$VARCALLER\t
-	$CNV\t
-	$ANNOTATOR\t
-	$CLEANUP\t
-	$NCPU\t
-	$VERSION\t
-	$NGSUSER\t
-	$DATE]"
-	
-	## Logfile 
-	LOGFILE=${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${DATE}.ngseasy_fastqc
-	## check and make log directory
-	if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/run_logs/" ]
-	then
-	mkdir ${PROJECT_DIR}/${PROJECT_ID}/run_logs/
-	fi
-	## check and make logfile
-	if [ ! -e "${LOGFILE}.log" ]
-	then
-	touch ${LOGFILE}.log
-	fi
-	logger_ngseasy "[ngseasy_fastqc]:Logging to [${LOGFILE}.log] "
+## read config_file
+logger_ngseasy "[ngseasy_fastqc]:
+[$PROJECT_ID\t
+$SAMPLE_ID\t
+$FASTQ1\t
+$FASTQ2\t
+$PROJECT_DIR\t 
+$DNA_PREP_LIBRARY_ID\t
+$NGS_PLATFORM\t
+$NGS_TYPE\t
+$BAIT\t
+$CAPTURE\t
+$FASTQC\t
+$TRIM\t
+$BSQR\t
+$REALN\t
+$ALIGNER\t
+$VARCALLER\t
+$CNV\t
+$ANNOTATOR\t
+$CLEANUP\t
+$NCPU\t
+$VERSION\t
+$NGSUSER\t
+$DATE]"
 
-	## OUTPUT SAMPLE DIR 
-	#
-	SOUT=${PROJECT_DIR}/${PROJECT_ID}/${SAMPLE_ID}
-	logger_ngseasy "[ngseasy_fastqc]:Sample Directory [${SOUT}] "
+## Logfile 
+LOGFILE=${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${DATE}.ngseasy_fastqc
+## check and make log directory
+if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/run_logs/" ]
+then
+mkdir ${PROJECT_DIR}/${PROJECT_ID}/run_logs/
+fi
+## check and make logfile
+if [ ! -e "${LOGFILE}.log" ]
+then
+touch ${LOGFILE}.log
+fi
+logger_ngseasy "[ngseasy_fastqc]:Logging to [${LOGFILE}.log] "
 
-	## check local dir exists
-	#
-	if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/${SAMPLE_ID}" ]
-	then
-	logger_ngseasy "[ngseasy_fastqc]: Cant Find Project directory. This is then end. Please Stop and check everything is ok " ${LOGFILE}
-	exit 1
+## OUTPUT SAMPLE DIR 
+#
+SOUT=${PROJECT_DIR}/${PROJECT_ID}/${SAMPLE_ID}
+logger_ngseasy "[ngseasy_fastqc]:Sample Directory [${SOUT}] "
 
-	else 
-	logger_ngseasy "[ngseasy_fastqc]: Setting OUTPUT directory [${SOUT}]" ${LOGFILE}
-	fi
+## check local dir exists
+#
+if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/${SAMPLE_ID}" ]
+then
+logger_ngseasy "[ngseasy_fastqc]: Cant Find Project directory. This is then end. Please Stop and check everything is ok " ${LOGFILE}
+exit 1
 
-	## check for fastq files exist
-	#
-	if [ ! -s "${SOUT}/fastq/${FASTQ1}" ] && [ ! -s "${SOUT}/fastq/${FASTQ2}" ]
-	then
-	logger_ngseasy "[ngseasy_fastqc]: Can't Find fastq files [${SOUT}/fastq/${FASTQ1}] and [${SOUT}/fastq/${FASTQ2}] in ${SOUT}/fastq/ " ${LOGFILE}
-	exit 1
-	fi
+else 
+logger_ngseasy "[ngseasy_fastqc]: Setting OUTPUT directory [${SOUT}]" ${LOGFILE}
+fi
 
-	## set new names for copied fastq files
-	#
-	# test for fomrat of suffix ie is it fastq or fq
-	# or _R1.fastq _R1.fq
-	# ILLUMINA : NA10831_ATCACG_L002_R1_001.fastq.gz
-	# Illumina FASTQ files use the following naming scheme:
-	# <sample name>_<barcode sequence>_L<lane (0-padded to 3 digits)>_R<read number>_<set number (0-padded to 3 digits>.fastq.gz
+## check for fastq files exist
+#
+if [ ! -s "${SOUT}/fastq/${FASTQ1}" ] && [ ! -s "${SOUT}/fastq/${FASTQ2}" ]
+then
+logger_ngseasy "[ngseasy_fastqc]: Can't Find fastq files [${SOUT}/fastq/${FASTQ1}] and [${SOUT}/fastq/${FASTQ2}] in ${SOUT}/fastq/ " ${LOGFILE}
+exit 1
+fi
+
+## set new names for copied fastq files
+#
+# test for fomrat of suffix ie is it fastq or fq
+# or _R1.fastq _R1.fq
+# ILLUMINA : NA10831_ATCACG_L002_R1_001.fastq.gz
+# Illumina FASTQ files use the following naming scheme:
+# <sample name>_<barcode sequence>_L<lane (0-padded to 3 digits)>_R<read number>_<set number (0-padded to 3 digits>.fastq.gz
 
 
-	if [[ "${FASTQ1}" == *_1.fastq.gz ]] 
-	then
+if [[ "${FASTQ1}" == *_1.fastq.gz ]] 
+then
 
-	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fastq.gz`
-	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fastq.gz`
-	
-	fq1_suffix="1.fastq.gz"
-	fq2_suffix="2.fastq.gz"
-	
-	FQ1=${rawFASTQ1}_${fq1_suffix}
-	FQ2=${rawFASTQ2}_${fq2_suffix}
-	
-	elif [[ "${FASTQ1}" == *_R1.fastq.gz ]] 
-	then
+rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fastq.gz`
+rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fastq.gz`
 
-	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _R1.fastq.gz`
-	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _R2.fastq.gz`
+fq1_suffix="1.fastq.gz"
+fq2_suffix="2.fastq.gz"
 
-	fq1_suffix="R1.fastq.gz"
-	fq2_suffix="R2.fastq.gz"
-	
-	FQ1=${rawFASTQ1}_${fq1_suffix}
-	FQ2=${rawFASTQ2}_${fq2_suffix}
-	
-	elif [[ "${FASTQ1}" == *_1.fq.gz ]] 
-	then
+FQ1=${rawFASTQ1}_${fq1_suffix}
+FQ2=${rawFASTQ2}_${fq2_suffix}
 
-	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fq.gz`
-	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fq.gz`
+elif [[ "${FASTQ1}" == *_R1.fastq.gz ]] 
+then
 
-	fq1_suffix="1.fq.gz"
-	fq2_suffix="2.fq.gz"  
+rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _R1.fastq.gz`
+rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _R2.fastq.gz`
 
-	FQ1=${rawFASTQ1}_${fq1_suffix}
-	FQ2=${rawFASTQ2}_${fq2_suffix}
-	
-	elif [[ "${FASTQ1}" == *_R1.fq.gz ]] 
-	then
+fq1_suffix="R1.fastq.gz"
+fq2_suffix="R2.fastq.gz"
 
-	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _R1.fq.gz`
-	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _R2.fq.gz`
-	
-	fq1_suffix="R1.fq.gz"
-	fq2_suffix="R2.fq.gz"  
+FQ1=${rawFASTQ1}_${fq1_suffix}
+FQ2=${rawFASTQ2}_${fq2_suffix}
 
-	FQ1=${rawFASTQ1}_${fq1_suffix}
-	FQ2=${rawFASTQ2}_${fq2_suffix}
-	
-	elif [[ "${FASTQ1}" == *_L*_R1_[0-9][0-9][0-9].fastq.gz ]] 
-	then
+elif [[ "${FASTQ1}" == *_1.fq.gz ]] 
+then
 
-	logger_ngseasy "[ngseasy_fastqc]:Illumina fastq naming scheme"
+rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fq.gz`
+rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fq.gz`
 
-	FQ1=${FASTQ1}
-	FQ2=${FASTQ2}
+fq1_suffix="1.fq.gz"
+fq2_suffix="2.fq.gz"  
 
-	
-	elif [[ "${FASTQ1}" == *_L*_R1_[0-9][0-9][0-9][0-9].fastq.gz ]] 
-	then
+FQ1=${rawFASTQ1}_${fq1_suffix}
+FQ2=${rawFASTQ2}_${fq2_suffix}
 
-	logger_ngseasy "[ngseasy_fastqc]:Illumina fastq naming scheme"
+elif [[ "${FASTQ1}" == *_R1.fq.gz ]] 
+then
 
-	FQ1=${FASTQ1}
-	FQ2=${FASTQ2}
-		
-	else
+rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _R1.fq.gz`
+rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _R2.fq.gz`
 
-	logger_ngseasy "[ngseasy_fastqc]: Fastq naming format not recognised for files [$FASTQ1] [$FASTQ2]" ${LOGFILE} 
-	logger_ngseasy "[ngseasy_fastqc]: This should be one of [_1.fastq.gz] [_1.fq.gz] [_R1.fastq.gz] [_R1.fq.gz]" ${LOGFILE} 
-	exit 1
-	fi        
+fq1_suffix="R1.fq.gz"
+fq2_suffix="R2.fq.gz"  
+
+FQ1=${rawFASTQ1}_${fq1_suffix}
+FQ2=${rawFASTQ2}_${fq2_suffix}
+
+elif [[ "${FASTQ1}" == *_L*_R1_[0-9][0-9][0-9].fastq.gz ]] 
+then
+
+logger_ngseasy "[ngseasy_fastqc]:Illumina fastq naming scheme"
+
+FQ1=${FASTQ1}
+FQ2=${FASTQ2}
+
+elif [[ "${FASTQ1}" == *_L*_R1_[0-9][0-9][0-9][0-9].fastq.gz ]] 
+then
+
+logger_ngseasy "[ngseasy_fastqc]:Illumina fastq naming scheme"
+
+FQ1=${FASTQ1}
+FQ2=${FASTQ2}
+
+else
+
+logger_ngseasy "[ngseasy_fastqc]: Fastq naming format not recognised for files [$FASTQ1] [$FASTQ2]" ${LOGFILE} 
+logger_ngseasy "[ngseasy_fastqc]: This should be one of [_1.fastq.gz] [_1.fq.gz] [_R1.fastq.gz] [_R1.fq.gz]" ${LOGFILE} 
+exit 1
+fi        
 
 
 	#-------------------------------------------------------------------#
diff --git a/bin/ngseasy_trimmomatic b/bin/ngseasy_trimmomatic
--- a/bin/ngseasy_trimmomatic
+++ b/bin/ngseasy_trimmomatic
@@ -1,39 +1,77 @@
-#!/bin/bash -x
-# Collection of NGSeasy Functions
-# Stephen Newhouse <stephen.j.newhouse@gmail.com>
-# Version 0.9.0
+#!/bin/bash
 
+################################################################
+# Program: ngseasy_trimmomatic
+# Version 1.0 
+# Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
+#################################################################
 
-##--------------------------------------------------##
-## Trimmomatic
-##--------------------------------------------------##
+## Set version and run date
+#
+NGSEASYVERSION="1.0"
+RUNDATE=`date +"%d%m%y"`
 
-#usage printing func
-usage()
-{
-cat << EOF
-  This script sets up the NGSeasy docker fastqc container and runs FastQC on raw fastq files
-  See NGSEasy containerized instructions.
-
-  ARGUMENTS:
-  -h      Flag: Show this help message
-  -c      NGSeasy project and run configureation file
-  -d      NGSeasy project directory
-
-  EXAMPLE USAGE:
-    
-    ngseasy_trimmomatic -c config.file.tsv -d project_directory
-
-EOF
+########################################################################################################
+## global logging fuction
+#
+function logger_ngseasy() {
+ message=${1}
+ mylogfile=${2}
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
 }
-#--------------------------------------------------------------------------------#
-#get options for command line args
+
+########################################################################################################
+## global usage
+#
+function ngseasy_trimmomatic_usage() {
+    echo "
+Program: ngseasy_trimmomatic
+Version 1.0
+Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
+
+usage:   ngseasy_trimmomatic -c <config_file> -d <project_directory>
+
+options:  -c  STRING	configuration file
+          -d  STRING	project directory
+          -h  NULL	show this message
+
+ngseasy_trimmomatic sets up the NGSeasy docker Trimmomatic container compbio/ngseasy-trimmomatic:VERSION and runs trimmomatic on raw fastq files.
+"
+}
+
+
+########################################################################################################
+## test if docker is intsalled and exit if not
+command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
+
+########################################################################################################
+## check and make ~/ngseasy_logs if needed
+#
+if [[ ! -e  ${HOME}/ngseasy_logs ]]
+then
+  mkdir ${HOME}/ngseasy_logs
+  global_run_logs="${HOME}/ngseasy_logs"
+fi
+
+########################################################################################################
+## Check options passed in.
+#
+if test -z "$2"
+then
+  logger_ngseasy "[ngseasy_fastqc]:ERROR:No options found"
+  ngseasy_fastqc_usage
+  exit 1
+fi
+
+########################################################################################################
+## get options for command line args
   while  getopts "hc:d:" opt
   do
 
       case ${opt} in
 	  h)
-	  usage #print help
+	  ngseasy_fastqc_usage #print help
 	  exit 0
 	  ;;
 	  
@@ -46,57 +84,266 @@ EOF
 	  ;; 
       esac
   done
-
-#--------------------------------------------------------------------------------#  
-#check config file exists.
+########################################################################################################  
+## check config file exists.
+#
 if [ ! -e "${config_tsv}" ] 
 then
-	    echo "ERROR :  ${config_tsv} does not exist....exiting "
-	    usage;
+	    logger_ngseasy "[ngseasy_fastqc]:ERROR : [${config_tsv}] does not exist....exiting "
+	    ngseasy_fastqc_usage;
 	    exit 1;
+else
+	    logger_ngseasy "[ngseasy_fastqc]:Configuration file found [${config_tsv}] "
 fi
 
-#--------------------------------------------------------------------------------#
-#check exists.
+########################################################################################################
+## check project_directory exists.
+#
 if [ ! -d "${project_directory}" ]
   then
-    echo "ERROR : project_directory ${project_directory} does not exist "
-    usage;
+    logger_ngseasy "[ngseasy_fastqc]:ERROR : project_directory [${project_directory}] does not exist "
+    ngseasy_fastqc_usage;
     exit 1;
+else
+	    logger_ngseasy "[ngseasy_fastqc]:Top Level Project Directory [${project_directory}] "
 fi
 
-#--------------------------------------------------------------------------------#
-#Read config file 
-while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
+########################################################################################################
+## check Num feilds in  ${config_tsv}
+#
+logger_ngseasy "[ngseasy_fastqc]:Reading [${config_tsv}] "
+
+numcols=`awk '{ print NF }' ${config_tsv} | sort -g | head -1`
+
+if [[  "$numcols" -lt 22 ]] 
+then
+	    logger_ngseasy "[ngseasy_fastqc]:ERROR : [${config_tsv}] format issue. Check your file! "
+	    exit 1;
+	    else 
+	    logger_ngseasy "[ngseasy_fastqc]:Numcols of [${config_tsv}] ok...proceeding... "	    
+fi
+
+########################################################################################################
+## Read config file 
+
+## check ${config_tsv}. is this a batch file or the orginal config file 
+#
+logger_ngseasy "[ngseasy_fastqc]:Checking [${config_tsv}] format" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+
+hasheader=`grep POJECT_ID ${config_tsv} | wc -l | awk '{print $1}'`
+
+if [[ "${config_tsv}" == *.batch.* ]]
+then
+	logger_ngseasy "[ngseasy_fastqc]:[${config_tsv}] is a BACTH file ie a subset of the original config file" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+	FILE=${config_tsv}
+
+## if header present then remove it
+elif [[ "$hasheader" -eq 1 ]]
+then
+	logger_ngseasy "[ngseasy_fastqc]:[${config_tsv}] header present. Removing this" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+	logger_ngseasy "[ngseasy_fastqc]:[cmd]:sed 1d \${config_tsv} > ${config_tsv}.tmp" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+	sed 1d ${config_tsv} > ${config_tsv}.tmp
+	FILE=${config_tsv}.tmp
+else
+	logger_ngseasy "[ngseasy_fastqc]:[${config_tsv}] is seemingly perfect" ${HOME}/ngseasy_logs/ngseasy.${config_tsv}.${RUNDATE}
+	FILE=${config_tsv}
+fi
+
+########################################################################################################
+## Read config and loop through all lines calling trimmomatic docker
+##
+while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18 f19 f20 f21 f22
 do
 
-# set varibales  
-  DATE=`date +"%d%m%y"`
-  PROJECT_ID=$f1
-  SAMPLE_ID=$f2
-  FASTQ1=$f3
-  FASTQ2=$f4
-  PROJECT_DIR=$f5 
-  DNA_PREP_LIBRARY_ID=$f6
-  NGS_PLATFORM=$f7
-  NGS_TYPE=$f8
-  BED_ANNO=$f9
-  PIPELINE=$f10
-  ALIGNER=$f11
-  VARCALLER=$f12
-  GTMODEGATK=$f13
-  CLEANUP=$f14
-  NCPU=$f15
-  VERSION=$f16
-  NGSUSER=$f17
+## set varibales  
+#
+PROJECT_ID=$f1
+SAMPLE_ID=$f2
+FASTQ1=$f3
+FASTQ2=$f4
+PROJECT_DIR=$f5
+DNA_PREP_LIBRARY_ID=$f6
+NGS_PLATFORM=$f7
+NGS_TYPE=$f8
+BAIT=$f9
+CAPTURE=$f10
+FASTQC=$f11
+TRIM=$f12
+BSQR=$f13
+REALN=$f14
+ALIGNER=$f15
+VARCALLER=$f16
+CNV=$f17
+ANNOTATOR=$f18
+CLEANUP=$f19
+NCPU=$f20
+VERSION=$f21
+NGSUSER=$f22
+DATE=`date +"%d%m%y"`
 
-#--------------------------------------------------------------------------------#
-#Logfile 
-LOGFILE=${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${DATE}
+## read config_file
+logger_ngseasy "[ngseasy_fastqc]:
+[$PROJECT_ID\t
+$SAMPLE_ID\t
+$FASTQ1\t
+$FASTQ2\t
+$PROJECT_DIR\t 
+$DNA_PREP_LIBRARY_ID\t
+$NGS_PLATFORM\t
+$NGS_TYPE\t
+$BAIT\t
+$CAPTURE\t
+$FASTQC\t
+$TRIM\t
+$BSQR\t
+$REALN\t
+$ALIGNER\t
+$VARCALLER\t
+$CNV\t
+$ANNOTATOR\t
+$CLEANUP\t
+$NCPU\t
+$VERSION\t
+$NGSUSER\t
+$DATE]"
 
-#--------------------------------------------------------------------------------#
-#OUTPUT SAMPLE DIR 
+## Logfile 
+LOGFILE=${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${DATE}.ngseasy_fastqc
+## check and make log directory
+if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/run_logs/" ]
+then
+mkdir ${PROJECT_DIR}/${PROJECT_ID}/run_logs/
+fi
+## check and make logfile
+if [ ! -e "${LOGFILE}.log" ]
+then
+touch ${LOGFILE}.log
+fi
+logger_ngseasy "[ngseasy_fastqc]:Logging to [${LOGFILE}.log] "
+
+## OUTPUT SAMPLE DIR 
+#
 SOUT=${PROJECT_DIR}/${PROJECT_ID}/${SAMPLE_ID}
+logger_ngseasy "[ngseasy_fastqc]:Sample Directory [${SOUT}] "
+
+## check local dir exists
+#
+if [ ! -d "${PROJECT_DIR}/${PROJECT_ID}/${SAMPLE_ID}" ]
+then
+logger_ngseasy "[ngseasy_fastqc]: Cant Find Project directory. This is then end. Please Stop and check everything is ok " ${LOGFILE}
+exit 1
+
+else 
+logger_ngseasy "[ngseasy_fastqc]: Setting OUTPUT directory [${SOUT}]" ${LOGFILE}
+fi
+
+## check for fastq files exist
+#
+if [ ! -s "${SOUT}/fastq/${FASTQ1}" ] && [ ! -s "${SOUT}/fastq/${FASTQ2}" ]
+then
+logger_ngseasy "[ngseasy_fastqc]: Can't Find fastq files [${SOUT}/fastq/${FASTQ1}] and [${SOUT}/fastq/${FASTQ2}] in ${SOUT}/fastq/ " ${LOGFILE}
+exit 1
+fi
+
+## set new names for copied fastq files
+#
+# test for fomrat of suffix ie is it fastq or fq
+# or _R1.fastq _R1.fq
+# ILLUMINA : NA10831_ATCACG_L002_R1_001.fastq.gz
+# Illumina FASTQ files use the following naming scheme:
+# <sample name>_<barcode sequence>_L<lane (0-padded to 3 digits)>_R<read number>_<set number (0-padded to 3 digits>.fastq.gz
+
+
+if [[ "${FASTQ1}" == *_1.fastq.gz ]] 
+then
+
+	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fastq.gz`
+	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fastq.gz`
+
+	fq1_suffix="1.fastq.gz"
+	fq2_suffix="2.fastq.gz"
+
+	FQ1=${rawFASTQ1}_${fq1_suffix}
+	FQ2=${rawFASTQ2}_${fq2_suffix}
+
+elif [[ "${FASTQ1}" == *_R1.fastq.gz ]] 
+then
+
+	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _R1.fastq.gz`
+	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _R2.fastq.gz`
+
+	fq1_suffix="R1.fastq.gz"
+	fq2_suffix="R2.fastq.gz"
+
+	FQ1=${rawFASTQ1}_${fq1_suffix}
+	FQ2=${rawFASTQ2}_${fq2_suffix}
+
+elif [[ "${FASTQ1}" == *_1.fq.gz ]] 
+then
+
+	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fq.gz`
+	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fq.gz`
+
+	fq1_suffix="1.fq.gz"
+	fq2_suffix="2.fq.gz"  
+
+	FQ1=${rawFASTQ1}_${fq1_suffix}
+	FQ2=${rawFASTQ2}_${fq2_suffix}
+
+elif [[ "${FASTQ1}" == *_R1.fq.gz ]] 
+then
+
+	rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _R1.fq.gz`
+	rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _R2.fq.gz`
+
+	fq1_suffix="R1.fq.gz"
+	fq2_suffix="R2.fq.gz"  
+
+	FQ1=${rawFASTQ1}_${fq1_suffix}
+	FQ2=${rawFASTQ2}_${fq2_suffix}
+
+elif [[ "${FASTQ1}" == *_L*_R1_[0-9][0-9][0-9].fastq.gz ]] 
+then
+
+	logger_ngseasy "[ngseasy_fastqc]:Illumina fastq naming scheme"
+
+	FQ1=${FASTQ1}
+	FQ2=${FASTQ2}
+
+elif [[ "${FASTQ1}" == *_L*_R1_[0-9][0-9][0-9][0-9].fastq.gz ]] 
+then
+
+	logger_ngseasy "[ngseasy_fastqc]:Illumina fastq naming scheme"
+
+	FQ1=${FASTQ1}
+	FQ2=${FASTQ2}
+
+else
+
+	logger_ngseasy "[ngseasy_fastqc]: Fastq naming format not recognised for files [$FASTQ1] [$FASTQ2]" ${LOGFILE} 
+	logger_ngseasy "[ngseasy_fastqc]: This should be one of [_1.fastq.gz] [_1.fq.gz] [_R1.fastq.gz] [_R1.fq.gz]" ${LOGFILE} 
+	exit 1
+fi    
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
 #--------------------------------------------------------------------------------#
 #Docker Output Dir: this is the mouned directory set by ngseasy_volumes_container
