minor

diff --git a/bin/ngseasy b/bin/ngseasy
--- a/bin/ngseasy
+++ b/bin/ngseasy
@@ -6,36 +6,32 @@
 # Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
 #################################################################
 
-## NGSeasy version
+## Set version and run date
+#
 NGSEASYVERSION="1.0"
+RUNDATE=`date +"%d%m%y"`
 
 ## test if docker is intsalled and exit if not
-command -v docker >/dev/null 2>&1 || { echo -e "Docker (https://docs.docker.com/installation/mac/) not installed.\nAborting." >&2; exit 1; }
+#
+command -v docker >/dev/null 2>&1 || { echo -e "Docker not installed.\nAborting." >&2; exit 1; }
 DOCKERVERSION=`docker version`
-echo -e "Docker Version:\n${DOCKERVERSION}"
-
-## TO DO : check if ngseasy scripts exist
-
-## check and make ~/ngseasy_logs if needed
-if [[ ! -e  ${HOME}/ngseasy_logs ]]
-then
-  mkdir ${HOME}/ngseasy_logs
-  global_run_logs="${HOME}/ngseasy_logs"
-  echo -e "making ${HOME}/ngseasy_logs"
-
-else
-    echo -e "${HOME}/ngseasy_logs exists"
-fi
+DOCKERINFO=`docker info`
+echo -e "\n"[`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]" 
+echo -e "\n---\nDocker Version\n---\n${DOCKERVERSION}\n---\n"Docker Info"\n---\n${DOCKERINFO}\n---\n"
+echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]"  >> ${HOME}/ngseasy_logs/${USER}.${RUNDATE}.NGSEASY.log
+echo -e "\n---\nDocker Version\n---\n${DOCKERVERSION}\n---\n"Docker Info"\n---\n${DOCKERINFO}\n---\n" >> ${HOME}/ngseasy_logs/${USER}.${RUNDATE}.NGSEASY.log
 
 ## global logging fuction
+#
 function logger_ngseasy() {
  message=${1}
  mylogfile=${2}
- echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[`pwd`]:[${USER}]:[`uname -a`]" >> ${mylogfile}.log >> ${global_run_logs}/ngseasy-run.log;
- echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[`pwd`]:[${USER}]:[`uname -a`]"
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
 }
 
 ## global usage
+#
 function usage_ngseasy() {
     echo "
 Program: ngseasy
@@ -50,15 +46,18 @@ options:  -c  configuration file
 "
 }
 
-## example config: https://docs.google.com/spreadsheets/d/1VWqmMffkVDnvOtRJGlPqOYzXWnIN_IONXQHDAawaN5Q/edit#gid=0
-
-## Check options passed in.
-if test -z "$2"
-  then
-  usage_ngseasy
-  exit 1
+## check and make ~/ngseasy_logs if needed
+#
+if [[ ! -e  ${HOME}/ngseasy_logs ]]
+then
+  mkdir ${HOME}/ngseasy_logs
+  global_run_logs="${HOME}/ngseasy_logs"
+  logger_ngseasy "making ${HOME}/ngseasy_logs" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+else
+  logger_ngseasy "${HOME}/ngseasy_logs exists" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
 fi
 
+## example config: https://docs.google.com/spreadsheets/d/1VWqmMffkVDnvOtRJGlPqOYzXWnIN_IONXQHDAawaN5Q/edit#gid=0
 
 ## get options for command line args
 while  getopts "hc:d:" opt
@@ -85,6 +84,14 @@ do
    esac
 done
 
+## Check options passed in.
+#
+if test -z "$2"
+  then
+  usage_ngseasy
+  exit 1
+fi
+
 ## check file and directory exist.
 if [[ ! -e "${config_tsv}" ]] 
   then
@@ -100,6 +107,21 @@ if [[ ! -d "${project_directory}" ]]
 	  echo -e "ERROR :  ${project_directory} does not exist\n"
 	  exit 1;
 fi
+
+
+# --- Start NGS Pipeline -------------------------------------------------------- #
+
+##-------------------------------------------------------------------------##
+## initiate projects
+#
+echo -e  "[ngseasy]:Calling ngseasy_initiate_project" 
+ngseasy_initiate_project -c ${config_tsv} -d ${project_directory}
+
+##-------------------------------------------------------------------------##
+## initiate fastq files
+#
+echo -e  "[ngseasy]:Calling ngseasy_initiate_fastq" 
+ngseasy_initiate_fastq -c ${config_tsv} -d ${project_directory}
 
 
 # --- Start NGS Pipeline -------------------------------------------------------- #
@@ -139,54 +161,53 @@ NGSUSER=$f22
 logger_ngseasy "[ngseasy]:Reading [${config_tsv}] " ${HOME}/ngseasy_logs/ngseasy.${POJECT_ID}.${USER}.$(date +"%d%m%y)"
 
 echo -e "
-[ngseasy]:Reading [${config_tsv}] \n
-[ngseasy]:Reading [${config_tsv}]:PROJECT_ID=[$PROJECT_ID] \n
-[ngseasy]:Reading [${config_tsv}]:SAMPLE_ID=[$SAMPLE_ID] \n
-[ngseasy]:Reading [${config_tsv}]:FASTQ1=[$FASTQ1] \n
-[ngseasy]:Reading [${config_tsv}]:FASTQ2=[$FASTQ2] \n
-[ngseasy]:Reading [${config_tsv}]:PROJECT_DIR=[$PROJECT_DIR] \n
-[ngseasy]:Reading [${config_tsv}]:DNA_PREP_LIBRARY_ID=[$DNA_PREP_LIBRARY_ID] \n
-[ngseasy]:Reading [${config_tsv}]:NGS_PLATFORM=[$NGS_PLATFORM] \n
-[ngseasy]:Reading [${config_tsv}]:NGS_TYPE=[$NGS_TYPE] \n
-[ngseasy]:Reading [${config_tsv}]:BAIT=[$BAIT] \n
-[ngseasy]:Reading [${config_tsv}]:CAPTURE=[$CAPTURE] \n
-[ngseasy]:Reading [${config_tsv}]:FASTQC=[$FASTQC] \n
-[ngseasy]:Reading [${config_tsv}]:TRIM=[$TRIM] \n
-[ngseasy]:Reading [${config_tsv}]:BSQR=[$BSQR] \n
-[ngseasy]:Reading [${config_tsv}]:REALN=$[$REALN] \n
-[ngseasy]:Reading [${config_tsv}]:ALIGNER=[$ALIGNER] \n
-[ngseasy]:Reading [${config_tsv}]:VARCALLER=[$VARCALLER] \n
-[ngseasy]:Reading [${config_tsv}]:CNV=[$CNV] \n
-[ngseasy]:Reading [${config_tsv}]:ANNOTATOR=[$ANNOTATOR] \n
-[ngseasy]:Reading [${config_tsv}]:CLEANUP=[$CLEANUP] \n
-[ngseasy]:Reading [${config_tsv}]:NCPU=[$NCPU] \n
-[ngseasy]:Reading [${config_tsv}]:VERSION=[$VERSION] \n
+[ngseasy]:Reading [${config_tsv}]\n
+[ngseasy]:Reading [${config_tsv}]:PROJECT_ID=[$PROJECT_ID]\n
+[ngseasy]:Reading [${config_tsv}]:SAMPLE_ID=[$SAMPLE_ID]\n
+[ngseasy]:Reading [${config_tsv}]:FASTQ1=[$FASTQ1]\n
+[ngseasy]:Reading [${config_tsv}]:FASTQ2=[$FASTQ2]\n
+[ngseasy]:Reading [${config_tsv}]:PROJECT_DIR=[$PROJECT_DIR]\n
+[ngseasy]:Reading [${config_tsv}]:DNA_PREP_LIBRARY_ID=[$DNA_PREP_LIBRARY_ID]\n
+[ngseasy]:Reading [${config_tsv}]:NGS_PLATFORM=[$NGS_PLATFORM]\n
+[ngseasy]:Reading [${config_tsv}]:NGS_TYPE=[$NGS_TYPE]\n
+[ngseasy]:Reading [${config_tsv}]:BAIT=[$BAIT]\n
+[ngseasy]:Reading [${config_tsv}]:CAPTURE=[$CAPTURE]\n
+[ngseasy]:Reading [${config_tsv}]:FASTQC=[$FASTQC]\n
+[ngseasy]:Reading [${config_tsv}]:TRIM=[$TRIM]\n
+[ngseasy]:Reading [${config_tsv}]:BSQR=[$BSQR]\n
+[ngseasy]:Reading [${config_tsv}]:REALN=$[$REALN]\n
+[ngseasy]:Reading [${config_tsv}]:ALIGNER=[$ALIGNER]\n
+[ngseasy]:Reading [${config_tsv}]:VARCALLER=[$VARCALLER]\n
+[ngseasy]:Reading [${config_tsv}]:CNV=[$CNV]\n
+[ngseasy]:Reading [${config_tsv}]:ANNOTATOR=[$ANNOTATOR]\n
+[ngseasy]:Reading [${config_tsv}]:CLEANUP=[$CLEANUP]\n
+[ngseasy]:Reading [${config_tsv}]:NCPU=[$NCPU]\n
+[ngseasy]:Reading [${config_tsv}]:VERSION=[$VERSION]\n
 [ngseasy]:Reading [${config_tsv}]:NGSUSER=[$NGSUSER]"
 
-logger_ngseasy "[ngseasy]:Reading [${config_tsv}] \n
-[ngseasy]:Reading [${config_tsv}]:PROJECT_ID=[$PROJECT_ID] \n
-[ngseasy]:Reading [${config_tsv}]:SAMPLE_ID=[$SAMPLE_ID] \n
-[ngseasy]:Reading [${config_tsv}]:FASTQ1=[$FASTQ1] \n
-[ngseasy]:Reading [${config_tsv}]:FASTQ2=[$FASTQ2] \n
-[ngseasy]:Reading [${config_tsv}]:PROJECT_DIR=[$PROJECT_DIR] \n
-[ngseasy]:Reading [${config_tsv}]:DNA_PREP_LIBRARY_ID=[$DNA_PREP_LIBRARY_ID] \n
-[ngseasy]:Reading [${config_tsv}]:NGS_PLATFORM=[$NGS_PLATFORM] \n
-[ngseasy]:Reading [${config_tsv}]:NGS_TYPE=[$NGS_TYPE] \n
-[ngseasy]:Reading [${config_tsv}]:BAIT=[$BAIT] \n
-[ngseasy]:Reading [${config_tsv}]:CAPTURE=[$CAPTURE] \n
-[ngseasy]:Reading [${config_tsv}]:FASTQC=[$FASTQC] \n
-[ngseasy]:Reading [${config_tsv}]:TRIM=[$TRIM] \n
-[ngseasy]:Reading [${config_tsv}]:BSQR=[$BSQR] \n
-[ngseasy]:Reading [${config_tsv}]:REALN=$[$REALN] \n
-[ngseasy]:Reading [${config_tsv}]:ALIGNER=[$ALIGNER] \n
-[ngseasy]:Reading [${config_tsv}]:VARCALLER=[$VARCALLER] \n
-[ngseasy]:Reading [${config_tsv}]:CNV=[$CNV] \n
-[ngseasy]:Reading [${config_tsv}]:ANNOTATOR=[$ANNOTATOR] \n
-[ngseasy]:Reading [${config_tsv}]:CLEANUP=[$CLEANUP] \n
-[ngseasy]:Reading [${config_tsv}]:NCPU=[$NCPU] \n
-[ngseasy]:Reading [${config_tsv}]:VERSION=[$VERSION] \n
-[ngseasy]:Reading [${config_tsv}]:NGSUSER=[$NGSUSER]
-" ${HOME}/ngseasy_logs/ngseasy.${POJECT_ID}.${USER}.$(date +"%d%m%y")
+logger_ngseasy "[ngseasy]:Reading [${config_tsv}]\n
+[ngseasy]:Reading [${config_tsv}]:PROJECT_ID=[$PROJECT_ID]\n
+[ngseasy]:Reading [${config_tsv}]:SAMPLE_ID=[$SAMPLE_ID]\n
+[ngseasy]:Reading [${config_tsv}]:FASTQ1=[$FASTQ1]\n
+[ngseasy]:Reading [${config_tsv}]:FASTQ2=[$FASTQ2]\n
+[ngseasy]:Reading [${config_tsv}]:PROJECT_DIR=[$PROJECT_DIR]\n
+[ngseasy]:Reading [${config_tsv}]:DNA_PREP_LIBRARY_ID=[$DNA_PREP_LIBRARY_ID]\n
+[ngseasy]:Reading [${config_tsv}]:NGS_PLATFORM=[$NGS_PLATFORM]\n
+[ngseasy]:Reading [${config_tsv}]:NGS_TYPE=[$NGS_TYPE]\n
+[ngseasy]:Reading [${config_tsv}]:BAIT=[$BAIT]\n
+[ngseasy]:Reading [${config_tsv}]:CAPTURE=[$CAPTURE]\n
+[ngseasy]:Reading [${config_tsv}]:FASTQC=[$FASTQC]\n
+[ngseasy]:Reading [${config_tsv}]:TRIM=[$TRIM]\n
+[ngseasy]:Reading [${config_tsv}]:BSQR=[$BSQR]\n
+[ngseasy]:Reading [${config_tsv}]:REALN=$[$REALN]\n
+[ngseasy]:Reading [${config_tsv}]:ALIGNER=[$ALIGNER]\n
+[ngseasy]:Reading [${config_tsv}]:VARCALLER=[$VARCALLER]\n
+[ngseasy]:Reading [${config_tsv}]:CNV=[$CNV]\n
+[ngseasy]:Reading [${config_tsv}]:ANNOTATOR=[$ANNOTATOR]\n
+[ngseasy]:Reading [${config_tsv}]:CLEANUP=[$CLEANUP]\n
+[ngseasy]:Reading [${config_tsv}]:NCPU=[$NCPU]\n
+[ngseasy]:Reading [${config_tsv}]:VERSION=[$VERSION]\n
+[ngseasy]:Reading [${config_tsv}]:NGSUSER=[$NGSUSER]" ${HOME}/ngseasy_logs/ngseasy.${POJECT_ID}.${USER}.$(date +"%d%m%y")
 
 ##-------------------------------------------------------------------------##
 ## fastqc
diff --git a/bin/ngseasy_fastqc b/bin/ngseasy_fastqc
--- a/bin/ngseasy_fastqc
+++ b/bin/ngseasy_fastqc
@@ -6,29 +6,23 @@
 # Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
 #################################################################
 
+## Set version and run date
+#
 NGSEASYVERSION="1.0"
-
-## test if docker is intsalled and exit if not
-command -v docker >/dev/null 2>&1 || { echo "I require Dokcer...but it's not installed.  Aborting." >&2; exit 1; }
-
-## check and make ~/ngseasy_logs if needed
-if [[ ! -e  ${HOME}/ngseasy_logs ]]
-then
-  mkdir ${HOME}/ngseasy_logs
-  global_run_logs="${HOME}/ngseasy_logs"
-fi
-
+RUNDATE=`date +"%d%m%y"`
 
 ## global logging fuction
+#
 function logger_ngseasy() {
  message=${1}
  mylogfile=${2}
- echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[`pwd`]:[${USER}]:[`uname -a`]" >> ${mylogfile}.log >> ${global_run_logs}/ngseasy-run.log;
- echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[`pwd`]:[${USER}]:[`uname -a`]"
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:${message}]":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:${message}]":[${USER}]:[`uname -a`]"
 }
 
 ## global usage
-function ngseasy_fastqc() {
+#
+function ngseasy_fastqc_usage() {
     echo "
 Program: ngseasy_fastqc
 Version 1.0
@@ -42,12 +36,23 @@ ngseasy_fastqc sets up the NGSeasy docker fastqc container compbio/ngseasy-fastq
 "
 }
 
+## test if docker is intsalled and exit if not
+command -v docker >/dev/null 2>&1 || { echo "I require Dokcer...but it's not installed.  Aborting." >&2; exit 1; }
+
+## check and make ~/ngseasy_logs if needed
+#
+if [[ ! -e  ${HOME}/ngseasy_logs ]]
+then
+  mkdir ${HOME}/ngseasy_logs
+  global_run_logs="${HOME}/ngseasy_logs"
+fi
 
 ## Check options passed in.
+#
 if test -z "$2"
 then
   logger_ngseasy "[ngseasy_fastqc]:ERROR:No options found"
-  ngseasy_fastqc
+  ngseasy_fastqc_usage
   exit 1
 fi
 
@@ -57,7 +62,7 @@ fi
 
       case ${opt} in
 	  h)
-	  ngseasy_fastqc #print help
+	  ngseasy_fastqc_usage #print help
 	  exit 0
 	  ;;
 	  
@@ -75,20 +80,20 @@ fi
 if [ ! -e "${config_tsv}" ] 
 then
 	    logger_ngseasy "[ngseasy_fastqc]:ERROR : [${config_tsv}] does not exist....exiting "
-	    ngseasy_fastqc;
+	    ngseasy_fastqc_usage;
 	    exit 1;
 else
-	    logger_ngseasy "[ngseasy_fastqc]:Configuration file found [${config_tsv}] "
+	    ngseasy_fastqc_usage "[ngseasy_fastqc]:Configuration file found [${config_tsv}] "
 fi
 
 #check project_directory exists.
 if [ ! -d "${project_directory}" ]
   then
     logger_ngseasy "[ngseasy_fastqc]:ERROR : project_directory [${project_directory}] does not exist "
-    ngseasy_fastqc;
+    ngseasy_fastqc_usage;
     exit 1;
 else
-	    logger_ngseasy "[ngseasy_fastqc]:Top Level Project Directory [${project_directory}] "
+	    ngseasy_fastqc_usage "[ngseasy_fastqc]:Top Level Project Directory [${project_directory}] "
 fi
 
 ## Read config file 
@@ -98,7 +103,7 @@ logger_ngseasy "[ngseasy_fastqc]:Reading [${config_tsv}] "
 ## trim gatk bsqr realign 
 ##
 
-while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
+while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18 f19 f20 f21
 do
 
 ## set varibales  
@@ -139,6 +144,10 @@ logger_ngseasy "[ngseasy_fastqc]:
   $NGS_TYPE\t
   $BED_ANNO\t
   $PIPELINE\t
+  $TRIM\t
+  $GATK\t
+  $BSQR\t
+  $REALN\t
   $ALIGNER\t
   $VARCALLER\t
   $GTMODEGATK\t
diff --git a/bin/ngseasy_initiate_project b/bin/ngseasy_initiate_project
--- a/bin/ngseasy_initiate_project
+++ b/bin/ngseasy_initiate_project
@@ -1,50 +1,63 @@
-#!/bin/bash
+#!/bin/bash -e -x
 
-# Collection of NGSeasy Functions
-# Stephen Newhouse <stephen.j.newhouse@gmail.com>
-# Version 0.9.0
+################################################################
+# Program: ngseasy_initiate_project
+# Version 1.0 
+# Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
+#################################################################
 
-##--------------------------------------------------##
-## create project directories
-##--------------------------------------------------##
+## Set version and run date
+#
+NGSEASYVERSION="1.0"
+RUNDATE=`date +"%d%m%y"`
 
-
-# NSGeasy Project Initiation
-# Makes Project and Sample Directories needed for NGSesy
-# Stephen Newhouse <stephen.j.newhouse@gmail.com>
-# Amos Folarin <afolarin@gmail.com>
-
-#usage printing func
-usage()
-{
-cat << EOF
-
-This script sets up the NGSeasy Project directories.
-
-Users must run this script before starting any NGS projects/runs 
-using NGSesy suite of tools.
-
-This ensures the correct directory structure is set up on your
-local machine. 
-
-Note: These directory names and structure are hard coded in the 
-NGSeasy scripts.  
-
-See NGSEasy containerized instructions.
-
-ARGUMENTS:
-	
-	-h      Flag: Show this help message
-	-c      Config pipeline file
-	-d      Base directory for (fastq_raw, reference_genomes_b37, gatk_resources, ngs_projects, ngseasy_scripts)
-
-EXAMPLE USAGE:
-	
-	ngseasy_initiate_project -c config.file.tsv -d /media/D/docker_ngs/ngseasy/
-
-EOF
+## global logging fuction
+#
+function logger_ngseasy() {
+ message=${1}
+ mylogfile=${2}
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]" >> ${mylogfile}.log;
+ echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"${message}":[${USER}]:[`uname -a`]"
 }
 
+## global usage
+#
+function ngseasy_initiate_project_usage() {
+    echo "
+Program: ngseasy_initiate_project
+Version 1.0
+Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
+
+ngseasy_initiate_project sets up the project file directories. You only need to run this once per project
+
+usage:   ngseasy_initiate_project -c <config_file> -d <project_directory>
+
+options: -h  show this message
+	-c   Config pipeline file
+	-d   Base directory for [ngs_projects](fastq_raw, reference_genomes_b37, gatk_resources, ngs_projects, ngseasy_scripts)
+"
+}
+
+## test if docker is intsalled and exit if not
+#
+command -v docker >/dev/null 2>&1 || { echo -e "Docker (https://docs.docker.com/installation/mac/) not installed.\nAborting." >&2; exit 1; }
+DOCKERVERSION=`docker version`
+echo -e "Docker Version:\n${DOCKERVERSION}"
+
+## check and make ~/ngseasy_logs if needed
+if [[ ! -e  ${HOME}/ngseasy_logs ]]
+then
+  mkdir ${HOME}/ngseasy_logs
+  global_run_logs="${HOME}/ngseasy_logs"
+fi
+
+## Check options passed in.
+if test -z "$2"
+then
+  logger_ngseasy "[ngseasy_initiate_project]:ERROR:No options found" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+  ngseasy_initiate_project_usage
+  exit 1
+fi
 
 #get options for command line args
 while  getopts "hc:d:" opt
@@ -84,133 +97,49 @@ done
   fi
   
 
-## Print to screen input 
-echo  " NGS config_file  : [${config_tsv}]"
-echo  " NGS host_vol_dir : [${host_vol_dir}]"
+## project list
+# config_tsv=config_file
+#
+# awk 'NR >1 {print $5"/"$1}' ${config_tsv} | sort | uniq > ${HOME}/ngseasy_tmp/Project_list
 
-echo  " Checking [${config_tsv}] format"
+## sample lists
+# config_tsv=config_file
+#
+awk 'NR >1 {print $5"/"$1"/"$2}' ${config_tsv} | sort | uniq > ${HOME}/ngseasy_tmp/ProjectBySample_list
 
-  numfeilds=`awk '{print NF}' ${config_tsv} | sort -gr | sed '1q'`
-  numsamples=`wc -l ${config_tsv} | awk '{print $1}'`
-echo  " Number of samples : [$numsamples]"
-    
-  if [ "$numfeilds" -ne "15" ]
-    then
-    echo  " WARNING! Number of fields not equal to 15 for one of your samples You appear to have missing data in [${config_file}]"
-    echo  " Check  [${config_file}] format"
-    echo  " The [config.file] should contain the following 15 columns for each sample:-"
-    echo  " 
-      POJECT_ID
-      SAMPLE_ID
-      FASTQ1
-      FASTQ2
-      PROJECT_DIR
-      DNA_PREP_LIBRARY_ID
-      NGS_PLATFORM
-      NGS_TYPE
-      BED_ANNO
-      PIPELINE
-      ALIGNER
-      VARCALLER
-      GTMODEGATK
-      CLEANUP
-      NCPU"
-    echo  " Data are [TAB] delimited and each line should end in a [NEW LINE]"
-      exit 1
-    else
-   echo  " All Good...Proceeding to read : [${config_tsv}]"
-  fi
-
-# begin reading config file line by line
   
-while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17
+## Read project_list
+#
+while read -r f1
 do
 
-# set varibales  
-  POJECT_ID=$f1
-  SAMPLE_ID=$f2
-  FASTQ1=$f3
-  FASTQ2=$f4
-# PROJECT_DIR=$f5
-  PROJECT_DIR=${host_vol_dir}
-  DNA_PREP_LIBRARY_ID=$f6
-  NGS_PLATFORM=$f7
-  NGS_TYPE=$f8
-  BED_ANNO=$f9
-  PIPELINE=$f10
-  ALIGNER=$f11
-  VARCALLER=$f12
-  GTMODEGATK=$f13
-  CLEANUP=$f14
-  NCPU=$f15
-	VERSION=$f16
-  NGSUSER=$f17
-  
-echo  "#------------------------------------------------------------#"
-echo  " Checking Project/Sample Directory Structure"
-echo  "#------------------------------------------------------------#"
-     echo " Checking Project Directory "   
-  if [ ! -d $PROJECT_DIR/${POJECT_ID} ]
-    then
-    echo  " Project Directory Does not exist" 
-    echo  " Setting up correct Project Directory"
-    echo ""
-    echo  " Making Directory : [$PROJECT_DIR/${POJECT_ID}/]"
-    echo  " Making Directory : [$PROJECT_DIR/${POJECT_ID}/config_files]"
-    echo  " Making Directory : [$PROJECT_DIR/${POJECT_ID}/cohort_vcfs]"
-    
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/config_files
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/cohort_vcfs
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/cohort_bams
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/cohort_reports
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/run_logs
-        
-  else
-    echo  " Project Directory Exists"
-  fi
+PROJECTDIRS=$f1
 
-     echo " Checking Sample Directory " 
-  if [ ! -d $PROJECT_DIR/${POJECT_ID}/$SAMPLE_ID ]  
-    then
-    echo " Sample Directory Does not exist"
-    echo " Setting up correct Sample Directory"
-    echo ""
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/fastq
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/tmp
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/alignments
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/vcf
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/reports
-        mkdir ${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/config_files
+    if [[ ! -d "$PROJECTDIRS" ]]
+        then
         
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}]"
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/fastq]"
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/tmp]"
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/alignments]"
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/vcf]"
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/reports]"
-    echo  " Making Sample Directory : [${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}/config_files]"
-  
-  else
-    echo  " Sample Directory Exists "
-  fi
-  
-echo ""
-echo  "#------------------------------------------------------------#"
-echo  " NGSeasy Project/Sample Settings "
-echo  "#------------------------------------------------------------#"
-DATE=`date +"%d%m%y"`
-echo  " Run Date : [$DATE]"
-echo  " Project_Id : [$POJECT_ID]" 
-echo  " Project Directory : [$PROJECT_DIR]"
-echo  " Platform : [$NGS_PLATFORM]"
-echo  " NGS Type : [$NGS_TYPE]"
-echo  " Clean up TRUE/FALE : [$CLEANUP]"
-echo  " Number of cpu : [$NCPU]"
-echo  " Output Directory : [${PROJECT_DIR}/${POJECT_ID}]"
-echo  " Saving Project configuration settings to : [${PROJECT_DIR}/${POJECT_ID}/config_files/project.config.file.${DATE}]"
-echo  "$DATE $f1 $f2 $f3 $f4 $f5 $f6 $f7 $f8 $f9 $f10 $f11 $f12 $f13 $f14 $f15 ${SAMPLE_ID}.${NGS_TYPE}.${NGS_PLATFORM}.${ALIGNER} ${PROJECT_DIR}/${POJECT_ID}" >> ${PROJECT_DIR}/${POJECT_ID}/config_files/project.config.file.${DATE};
-  
-done < ${config_tsv}
+            logger_ngseasy "[ngseasy_initiate_project]:[${PROJECTDIRS}] Does Not Exist" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            logger_ngseasy "[ngseasy_initiate_project]:Making Project Directories..." ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}/fastq" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}/fastq 
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}/tmp" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}/tmp 
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}/alignments" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}/alignments 
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}/vcf" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}/vcf 
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}/reports" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}/reports 
+            logger_ngseasy "[ngseasy_initiate_project]:[CMD: mkdir -p ${PROJECTDIRS}/fastq" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+            mkdir -p ${PROJECTDIRS}/config_files
+            
+        else
+            logger_ngseasy "[ngseasy_initiate_project]:[${PROJECTDIRS}] Exist" ${HOME}/ngseasy_logs/${RUNDATE}.NGSEASY
+    fi
 
+done < ${HOME}/ngseasy_tmp/ProjectBySample_list
+## remove lists
+#
+    rm ${HOME}/ngseasy_tmp/ProjectBySample_list
