dev updates

diff --git a/bin/ngseasy_fastqc b/bin/ngseasy_fastqc
--- a/bin/ngseasy_fastqc
+++ b/bin/ngseasy_fastqc
@@ -146,13 +146,12 @@ This is is optomised for PE data, and calls 2 threads as default to process the 
 ## Check options passed in.
 ###########################################################################################
 
-if [[ -z "$config_tsv" ]]; then
-    echo -e "ERROR: No options were passed. Exiting"
-    sleep 1s
-    ngseasy_fastqc_usage
-    sleep 1s
-    exit 1
+if test -z "$2"; then
+  echo -e "ERROR: No options were passed. Exiting"
+  usage
+  exit 1
 fi
+
 ########################################################################################################
 ## check config file exists.
 ########################################################################################################
