dev updates 30 June 2015

diff --git a/bin/ngseasy_alignment b/bin/ngseasy_alignment
--- a/bin/ngseasy_alignment
+++ b/bin/ngseasy_alignment
@@ -127,17 +127,6 @@ config_tsv=""
 project_directory=""
 
 ########################################################################################################
-## Check options passed in.
-########################################################################################################
-if [[  -z "$config_tsv" ]]
-then
-  logger_ngseasy "[${NGSEASY_STEP}]:\nERROR:No options found"
-  ngseasy_alignment_usage
-  exit 1
-  sleep 1s
-fi
-
-########################################################################################################
 ## get options for command line args
 ########################################################################################################
   while  getopts "hc:d:" opt
@@ -158,6 +147,17 @@ fi
 	  ;;
       esac
   done
+
+########################################################################################################
+## Check options passed in.
+########################################################################################################
+  if [[  -z "$config_tsv" ]]
+  then
+    logger_ngseasy "[${NGSEASY_STEP}]:\nERROR:No options found"
+    ngseasy_alignment_usage
+    exit 1
+    sleep 1s
+fi
 
 ########################################################################################################
 ## check config file exists.
diff --git a/bin/ngseasy_realn b/bin/ngseasy_realn
--- a/bin/ngseasy_realn
+++ b/bin/ngseasy_realn
@@ -42,25 +42,27 @@ KNOWN_INDELS=""
 KNOWN_SNPS_1000G=""
 KNOWN_SNPS_OMNI=""
 KNOWN_SNPS_b138=""
+
 ########################################################################################################
 ## test if docker is intsalled and exit if not
+########################################################################################################
 command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## Set version and run date
-#
+########################################################################################################
 NGSEASYVERSION="1.0-r001"
 RUNDATE=`date +"%d%m%y"`
 NGSEASY_STEP="ngseasy_realn"
 
 ########################################################################################################
 ## docker run command
-#
+########################################################################################################
 DOCKER_RUN="docker run -P -w /home/pipeman -e HOME=/home/pipeman -e USER=pipeman --user pipeman"
 
 ########################################################################################################
 ## global logging fuction
-#
+########################################################################################################
 function logger_ngseasy() {
  message=${1}
  mylogfile=${2}
@@ -70,7 +72,7 @@ function logger_ngseasy() {
 
 ########################################################################################################
 ## global usage
-#
+########################################################################################################
 function ngseasy_realn_usage() {
     echo "
 Program: ngseasy_realn
@@ -89,7 +91,7 @@ ngseasy_realn sets up the NGSeasy docker containers for Indel Realignment using 
 
 ########################################################################################################
 ## check and make ~/ngseasy_logs if needed
-#
+########################################################################################################
 if [[ ! -e  ${HOME}/ngseasy_logs ]]
 then
   mkdir ${HOME}/ngseasy_logs
@@ -97,17 +99,8 @@ then
 fi
 
 ########################################################################################################
-## Check options passed in.
-#
-if test -z "$2"
-then
-  logger_ngseasy "[${NGSEASY_STEP}]:ERROR:No options found"
-  ngseasy_realn_usage
-  exit 1
-fi
-
-########################################################################################################
 ## get options for command line args
+########################################################################################################
   while  getopts "hc:d:" opt
   do
 
@@ -128,8 +121,19 @@ fi
   done
 
 ########################################################################################################
+## Check options passed in.
+########################################################################################################
+if [[  -z "$config_tsv" ]]
+    then
+      logger_ngseasy "[${NGSEASY_STEP}]:\nERROR:No options found"
+      ngseasy_realn_usage
+      exit 1
+      sleep 1s
+fi
+
+########################################################################################################
 ## check config file exists.
-#
+########################################################################################################
 if [[ ! -e "${config_tsv}" ]]
 then
       logger_ngseasy "[${NGSEASY_STEP}]:ERROR : [${config_tsv}] does not exist or can not be found. Exiting "
@@ -141,7 +145,7 @@ fi
 
 ########################################################################################################
 ## check project_directory exists.
-#
+########################################################################################################
 if [[ ! -d "${project_directory}" ]]
   then
     logger_ngseasy "[${NGSEASY_STEP}]:ERROR : project_directory [${project_directory}] does not exist "
@@ -153,7 +157,7 @@ fi
 
 ########################################################################################################
 ## check Num feilds in  ${config_tsv}
-#
+########################################################################################################
 logger_ngseasy "[${NGSEASY_STEP}]:Reading [${config_tsv}] "
 logger_ngseasy "[${NGSEASY_STEP}]:Checking number of feilds in  [${config_tsv}] "
 
