dev updates 090315

diff --git a/bin/ngseasy_bsqr b/bin/ngseasy_bsqr
--- a/bin/ngseasy_bsqr
+++ b/bin/ngseasy_bsqr
@@ -374,7 +374,25 @@ logger_ngseasy "[ngseasy_bsqr]:Setting BAM prefix to [${BAM_PREFIX}] " ${LOGFILE
 ## BSQR
 ########################################################################################################
 
-if [[ "${BSQR}" == "no-bsqr" ]]; then
+if  [[ -e "${SOUT}/alignments/${BAM_PREFIX}.dupemk.bam-bsqr.bam" ]]; then
+  
+  logger_ngseasy "[ngseasy_bsqr]:Skipping Base quality score recalibration. Looks like you already ran it [${SOUT}/alignments/${BAM_PREFIX}.dupemk.bam-bsqr.bam]" ${LOGFILE}
+  logger_ngseasy "[ngseasy_alignment]:Checking file sizes" ${LOGFILE}
+
+BAMSIZE=$(du -sb ${SOUT}/alignments/${BAM_PREFIX}.bam-bsqr.bam | awk '{ print ${1} }')
+FQSIZE=$(du -sb ${SOUT}/fastq/${FQ1} | awk '{ print ${1} }')
+
+if [[ "${FQSIZE}" -gt "${BAMSIZE}" ]]; then
+  logger_ngseasy "[ngseasy_alignment]:ERROR:FASTQ bigger than BAM. Something wrong here" ${LOGFILE}
+  logger_ngseasy "[ngseasy_alignment]:Alignment may have broke at somepoint" ${LOGFILE}
+  logger_ngseasy "[ngseasy_alignment]:Check your output" ${LOGFILE}
+  logger_ngseasy "[ngseasy_alignment]:Try and re-run ngseasy_alignment" ${LOGFILE}
+  logger_ngseasy "[ngseasy_alignment]:Exiting" ${LOGFILE}
+  sleep 2s
+  exit 1
+else
+  
+elif [[ "${BSQR}" == "no-bsqr" ]]; then
   
   logger_ngseasy "[ngseasy_bsqr]:Skipping Base quality score recalibration" ${LOGFILE}
 
@@ -398,7 +416,10 @@ elif [[ "${BSQR}" == "bam-bsqr" ]]; then
   --dbsnp ${DBSNP} \
   --storeQualTag OQ \
   --maxBaseQual 40;
+wait
 
+## GATK BaseRecalibrator and PrintReads
+#
   elif [[ "${BSQR}" == "gatk-bsqr"  ]]; then
 
       BAMIN=${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.bam
@@ -428,6 +449,8 @@ elif [[ "${BSQR}" == "bam-bsqr" ]]; then
   -I ${BAMIN} \
   -BSQR ${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.bam. recal_data.table \
   -0 ${BAMOUT}"
+wait
+
 else
   logger_ngseasy "[ngseasy_bsqr]:ERROR: Do not recognise BSQR option [${BSQR}]. This should be one or [bam-bsqr] [gatk-bsqr] or [no-bsqr]. Exiting" ${LOGFILE}
   sleep 2s
