dev updates 050315

diff --git a/bin/ngseasy b/bin/ngseasy
--- a/bin/ngseasy
+++ b/bin/ngseasy
@@ -11,13 +11,21 @@
 NGSEASYVERSION="1.0"
 RUNDATE=`date +"%d%m%y"`
 
+echo -e "\n\n###########################################################################################"
+echo -e "# Program: ngseasy"
+echo -e "# Version ${NGSEASYVERSION}"
+echo -e "# Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)"
+echo -e "###########################################################################################\n\n"
+
 ###########################################################################################
 ## test if docker is intsalled and exit if not
 ###########################################################################################
 
-command -v docker >/dev/null 2>&1 || { echo -e "Docker not installed.\nAborting." >&2; exit 1; }
+command -v docker >/dev/null 2>&1 || { echo -e "\n\nDocker not installed.\n\nAborting....." >&2; exit 1; }
+echo -e "Checking Docker Version and Info\n"
 DOCKERVERSION=`docker version`
 DOCKERINFO=`docker info`
+
 echo -e "\n"[`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]" 
 echo -e "\n----------------------------------\nDocker Version\n----------------------------------\n${DOCKERVERSION}\n----------------------------------\n"Docker Info"\n----------------------------------\n${DOCKERINFO}\n----------------------------------\n"
 echo -e [`date`]":[NGSEASY:${NGSEASYVERSION}]:"[Log:START]":[${USER}]:[`uname -a`]"  >> ${HOME}/ngseasy_logs/${USER}.${RUNDATE}.NGSEASY.log
