dev updates 030315

diff --git a/bin/ngseasy_alignment b/bin/ngseasy_alignment
--- a/bin/ngseasy_alignment
+++ b/bin/ngseasy_alignment
@@ -6,6 +6,13 @@
 # Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
 #################################################################
 
+#################################################################
+
+########################################################################################################
+## test if docker is intsalled and exit if not
+command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
+
+########################################################################################################
 ## Set version and run date
 #
 NGSEASYVERSION="1.0"
@@ -27,27 +34,6 @@ function logger_ngseasy() {
 }
 
 ########################################################################################################
-## Select Genome Build
-#
-# GENOMEBUILD="b37"
-GENOMEBUILD="hg19"
-
-if [[ "${GENOMEBUILD}" == "b37" ]]; then
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_b37"
-  GENOMEINDEX=${REFDIR}/human_g1k_v37
-  logger_ngseasy "[ngseasy_alignment]: Genome Build [${GENOMEBUILD}]"
-
-elif [[ "${GENOMEBUILD}" == "hg19" ]]; then
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_hg19"
-  GENOMEINDEX=${REFDIR}/ucsc.hg19
-  logger_ngseasy "[ngseasy_alignment]: Genome Build [${GENOMEBUILD}]"
-
-else
-  logger_ngseasy "No genome selected. Exiting. Choose one of [b37] or [hg19]"
-  exit 1
-fi
-
-########################################################################################################
 ## global usage
 #
 function ngseasy_alignment_usage() {
@@ -67,10 +53,6 @@ ngseasy_alignment sets up the NGSeasy docker containers for your aligner of choi
 This is is optomised for Illumina PE data
 "
 }
-
-########################################################################################################
-## test if docker is intsalled and exit if not
-command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## check and make ~/ngseasy_logs if needed
@@ -236,28 +218,30 @@ $NGSUSER\t
 $DATE]"
 
 ########################################################################################################
-## Select Genome Build
-#
-
-if [[ "${GENOMEBUILD}" == "b37" ]]; then
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_b37"
-  GENOMEINDEX=${REFDIR}/human_g1k_v37
-  logger_ngseasy "[ngseasy_alignment]: Genome Build [${GENOMEBUILD}]"
-
-elif [[ "${GENOMEBUILD}" == "hg19" ]]; then
-  REFDIR="/home/pipeman/ngs_projects/reference_genomes_hg19"
-  GENOMEINDEX=${REFDIR}/ucsc.hg19
-  logger_ngseasy "[ngseasy_alignment]: Genome Build [${GENOMEBUILD}]"
-
-else
-  logger_ngseasy "No genome selected. Exiting. Choose one of [b37] or [hg19]"
-  exit 1
-fi
-
-########################################################################################################
 ## LOGFILE 
 #
 LOGFILE=${PROJECT_DIR}/${PROJECT_ID}/run_logs/${SAMPLE_ID}.${TRIM}.${BSQR}.${REALN}.${ALIGNER}.${RUNDATE}.ngseasy_alignment
+
+########################################################################################################
+## Select Genome Build
+#
+logger_ngseasy "[ngseasy_alignment]:Checking genome selected]"  ${LOGFILE}
+
+if [[ "${GENOMEBUILD}" -eq "b37" ]]; then
+  REFDIR="/home/pipeman/ngs_projects/reference_genomes_b37"
+  GENOMEINDEX=${REFDIR}/human_g1k_v37
+  logger_ngseasy "[ngseasy_alignment]: Genome Build [${GENOMEBUILD}]" ${LOGFILE}
+
+elif [[ "${GENOMEBUILD}" -eq "hg19" ]]; then
+  REFDIR="/home/pipeman/ngs_projects/reference_genomes_hg19"
+  GENOMEINDEX=${REFDIR}/ucsc.hg19
+  logger_ngseasy "[ngseasy_alignment]: Genome Build [${GENOMEBUILD}]"  ${LOGFILE}
+
+else
+  logger_ngseasy "[ngseasy_alignment]:No genome selected. Exiting. Choose one of [b37] or [hg19]"  ${LOGFILE}
+  exit 1
+fi
+
 
 ########################################################################################################
 ## check and make log directory
@@ -317,7 +301,7 @@ SOUTDocker=${DOCKERHOME}/${PROJECT_ID}/${SAMPLE_ID}
 logger_ngseasy "[ngseasy_alignment]:Docker Output directory [${SOUTDocker}]" ${LOGFILE}
 
 ########################################################################################################
-## check if Trimmed data alread exists 
+## check if Trimmed data alread exists and use it
 #
 if [ ! -s "${SOUT}/fastq/${SAMPLE_ID}_${NGS_TYPE}_${TRIM}_1.filtered.fastq.gz" ] && [ ! -s "${SOUT}/fastq/${SAMPLE_ID}_${NGS_TYPE}_${TRIM}_2.filtered.fastq.gz" ]
 then
@@ -583,7 +567,7 @@ logger_ngseasy " START ${ALIGNER} Basic Alignment" ${LOGFILE}
     logger_ngseasy " END Basic ${ALIGNER} Basic Alignment" ${LOGFILE}
 
 else
-  logger_ngseasy " No Aligner selected. Or aligner not recognised. Should be one of bwa, stampy, novoalign, snap or bowtie2" ${LOGFILE} 
+  logger_ngseasy " No Aligner selected. Or aligner not recognised. Should be one of [bwa], [stampy], [novoalign], [snap] or [bowtie2]" ${LOGFILE} 
   exit 1
 
 fi
diff --git a/bin/ngseasy_trimmomatic b/bin/ngseasy_trimmomatic
--- a/bin/ngseasy_trimmomatic
+++ b/bin/ngseasy_trimmomatic
@@ -6,6 +6,11 @@
 # Author: Stephen Newhouse (stephen.j.newhouse@gmail.com)
 #################################################################
 
+########################################################################################################
+## test if docker is intsalled and exit if not
+command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
+
+########################################################################################################
 ## Set version and run date
 #
 NGSEASYVERSION="1.0"
@@ -44,11 +49,6 @@ options:  -c  STRING	configuration file
 ngseasy_trimmomatic sets up the NGSeasy docker Trimmomatic container compbio/ngseasy-trimmomatic:VERSION and runs trimmomatic on raw fastq files.
 "
 }
-
-
-########################################################################################################
-## test if docker is intsalled and exit if not
-command -v docker >/dev/null 2>&1 || { echo "I require Docker...but it's not installed.  Aborting." >&2; exit 1; }
 
 ########################################################################################################
 ## check and make ~/ngseasy_logs if needed
@@ -404,6 +404,8 @@ qcSEFQ2=${SOUTDocker}/fastq/${SAMPLE_ID}.${NGS_TYPE}.${DNA_PREP_LIBRARY_ID}.${TR
 #
 BAM_PREFIX=${SAMPLE_ID}.${NGS_TYPE}.${DNA_PREP_LIBRARY_ID}.${NGS_PLATFORM}.${TRIM}.${ALIGNER}.${GENOMEBUILD}
 
+logger_ngseasy "[ngseasy_trimmomatic]:BAM Prefix [${BAM_PREFIX}]" ${LOGFILE}
+
 ########################################################################################################
 #---------------------------------------Trimmomatic----------------------------------------------------#
 ########################################################################################################
@@ -414,9 +416,9 @@ logger_ngseasy "[ngseasy_trimmomatic]:START Trimmomatic+FastQC filtered Fastq fi
 #
 logger_ngseasy "[ngseasy_trimmomatic]:checking if trimmed data exists" ${LOGFILE}
 
-if [ -s "${SOUT}/fastq/${rawFASTQ1}_1.filtered.fastq.gz" ] && [ -s "${SOUT}/fastq/${rawFASTQ2}_2.filtered.fastq.gz" ]
+if [ -s "${SOUT}/fastq/${SAMPLE_ID}.${NGS_TYPE}.${DNA_PREP_LIBRARY_ID}.${TRIM}_1.filtered.fastq.gz" ] && [ -s "${SOUT}/fastq/${SAMPLE_ID}.${NGS_TYPE}.${DNA_PREP_LIBRARY_ID}.${TRIM}.2.filtered.fastq.gz" ]
 then
-	logger_ngseasy "[ngseasy_trimmomatic]:Trimmed Data already exists...skipping [ngseasy_trimmomatic]" ${LOGFILE}
+	logger_ngseasy "[ngseasy_trimmomatic]:PE Trimmed Data already exists...skipping [ngseasy_trimmomatic]" ${LOGFILE}
 	exit 0
 
 elif [[ "$TRIMM" == "atrim" ]]; then
@@ -425,7 +427,8 @@ elif [[ "$TRIMM" == "atrim" ]]; then
 ########################################################################################################
 ## run compbio/ngseasy-trimmomatic
 # 
-logger_ngseasy "[ngseasy_trimmomatic]:START qc of raw fastq files. Adaptor and read quality trimming" ${LOGFILE}
+logger_ngseasy "[ngseasy_trimmomatic]:START qc of raw fastq files" ${LOGFILE}
+logger_ngseasy "[ngseasy_trimmomatic]:TRIMM set to [$TRIMM] - adaptor trim. Adaptor and read quality trimming" ${LOGFILE}
 
 ## make parallel cmd
 #
@@ -491,7 +494,8 @@ logger_ngseasy "[ngseasy_trimmomatic]:FastQC post Trimmomatic" ${LOGFILE}
 #
 elif [[ "$TRIMM" == "btrim" ]]; then
 
-logger_ngseasy "[ngseasy_trimmomatic]:START qc of raw fastq files. No adaptor trimming. Just read quality trimming " ${LOGFILE}
+logger_ngseasy "[ngseasy_trimmomatic]:START qc of raw fastq files" ${LOGFILE}
+logger_ngseasy "[ngseasy_trimmomatic]:TRIMM set to [$TRIMM] - basic trim. Just read quality trimming. No adaptor trimming" ${LOGFILE}
 
 ## make parallel cmd
 #
@@ -548,7 +552,7 @@ logger_ngseasy "[ngseasy_trimmomatic]:START FastQC post Trimmomatic" ${LOGFILE}
 	${qcSEFQ1} \
 	${qcSEFQ2}
 
-elif [[ "$TRIMM" == "no-trim" ]]; then
+elif [[ "${TRIMM}" == "notrim" ]]; then
 	logger_ngseasy "[ngseasy_trimmomatic]:Skipping quality control of raw fastq reads. NOT RECOMMENDED" ${LOGFILE}
 else 
 	logger_ngseasy "[ngseasy_trimmomatic]:ERROR Cant recognise TRIMM option. Should be one of [atrim] [btrim] or [no-trim]" ${LOGFILE}
